version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: tripnest
      POSTGRES_PASSWORD: tripnest
      POSTGRES_DB: tripnest
    ports:
      - '5432:5432'
    volumes:
      - tripnest_postgres_data:/var/lib/postgresql/data

volumes:
  tripnest_postgres_data:
